!
! Copyright 2011 ECMWF
! 
! This software was developed at ECMWF for evaluation
! and may be used for academic and research purposes only.
! The software is provided as is without any warranty.
! 
! This software can be used, copied and modified but not
! redistributed or sold. This notice must be reproduced
! on each copy made.
!

!> Handle model configuration for the IFS model

MODULE TYPE_MODEL

USE MODEL_GENERAL_CONF_MOD        , ONLY : MODEL_GENERAL_CONF_TYPE
USE MODEL_ATMOS_OCEAN_COUPLING_MOD, ONLY : MODEL_ATMOS_OCEAN_COUPLING_TYPE
!USE MODEL_LAM_COUPLING_MOD        , ONLY : MODEL_LAM_COUPLING_TYPE
USE MODEL_DYNAMICS_MOD            , ONLY : MODEL_DYNAMICS_TYPE
USE MODEL_PHYSICS_GENERAL_MOD     , ONLY : MODEL_PHYSICS_GENERAL_TYPE
USE MODEL_PHYSICS_ECMWF_MOD       , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD  , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE MODEL_PHYSICS_AEROSOL_MOD     , ONLY : MODEL_PHYSICS_AEROSOL_TYPE
USE MODEL_PHYSICS_RADIATION_MOD   , ONLY : MODEL_PHYSICS_RADIATION_TYPE
USE MODEL_PHYSICS_STOCHAST_MOD    , ONLY : MODEL_PHYSICS_STOCHAST_TYPE
USE MODEL_PHYSICS_MF_MOD          , ONLY : MODEL_PHYSICS_MF_TYPE
USE MODEL_CHEM_MOD                , ONLY : MODEL_CHEM_TYPE
USE MODEL_DIAGNOSTICS_MOD         , ONLY : MODEL_DIAGNOSTICS_TYPE
USE YOEWCOU                       , ONLY : TEWCOU
!
USE YEMLBC_MODEL                  , ONLY : TELBC_MODEL

IMPLICIT NONE

TYPE, PUBLIC :: MODEL
!!  PRIVATE
  LOGICAL                               :: LINEAR_MODEL=.FALSE. ! As seen by OOPS
  TYPE(MODEL_GENERAL_CONF_TYPE)         :: YRML_GCONF 
  TYPE(MODEL_ATMOS_OCEAN_COUPLING_TYPE) :: YRML_AOC
!  TYPE(MODEL_LAM_COUPLING_TYPE)         :: YRML_LC   ! Removed 
  TYPE(MODEL_DYNAMICS_TYPE)             :: YRML_DYN
  TYPE(MODEL_PHYSICS_GENERAL_TYPE)      :: YRML_PHY_G
  TYPE(MODEL_PHYSICS_ECMWF_TYPE)        :: YRML_PHY_EC
  TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE)   :: YRML_PHY_SLIN
  TYPE(MODEL_PHYSICS_AEROSOL_TYPE)      :: YRML_PHY_AER
  TYPE(MODEL_PHYSICS_RADIATION_TYPE)    :: YRML_PHY_RAD
  TYPE(MODEL_PHYSICS_STOCHAST_TYPE)     :: YRML_PHY_STOCH
  TYPE(MODEL_PHYSICS_MF_TYPE)           :: YRML_PHY_MF 
  TYPE(MODEL_CHEM_TYPE)                 :: YRML_CHEM
  TYPE(MODEL_DIAGNOSTICS_TYPE)          :: YRML_DIAG
  TYPE(TEWCOU)                          :: YREWCOU
  TYPE(TELBC_MODEL), POINTER            :: YRML_LBC => NULL()

  !-------

  CONTAINS

    PROCEDURE, PASS :: PRINT => PRINT_MODEL_CONFIGURATION
    FINAL :: MODEL_FINAL

END TYPE MODEL

!------------------------------------------------------------------------
CONTAINS

SUBROUTINE PRINT_MODEL_CONFIGURATION(SELF,CDSTRING,KOUTNO)
  USE PARKIND1, ONLY : JPIM
  USE YOMLUN,   ONLY : NULOUT
  IMPLICIT NONE
  CLASS(MODEL),       INTENT(IN)           :: SELF
  CHARACTER(LEN=*),   INTENT(IN)           :: CDSTRING
  INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KOUTNO

  INTEGER(KIND=JPIM) :: IOUTNO,ITOPDEPTH
  LOGICAL :: LLOPENED = .FALSE.

  ITOPDEPTH = 0

  IF (PRESENT(KOUTNO)) THEN
    IOUTNO = KOUTNO
    INQUIRE(KOUTNO,OPENED=LLOPENED)
    IF (LLOPENED) CLOSE(IOUTNO)
    OPEN(IOUTNO, FILE='model_configuration.txt', ACTION='WRITE', FORM='FORMATTED', POSITION='APPEND')
  ELSE
    IOUTNO = NULOUT
  ENDIF

  WRITE(IOUTNO,*) '=============================================='
  WRITE(IOUTNO,*) '=============================================='
  WRITE(IOUTNO,*) 'MODEL Object print of internal state'
  WRITE(IOUTNO,*) ''
  WRITE(IOUTNO,*) CDSTRING 


  CALL SELF%YRML_GCONF%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YRML_AOC%PRINT(ITOPDEPTH,IOUTNO)
  !!CALL SELF%YRML_LC%PRINT(ITOPDEPTH,IOUTNO) !! limited-area coupling, worry about this later
  CALL SELF%YRML_DYN%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YRML_PHY_G%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YRML_PHY_EC%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YRML_PHY_SLIN%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YRML_PHY_AER%PRINT(ITOPDEPTH,IOUTNO)
! CALL SELF%YRML_PHY_RAD%PRINT(ITOPDEPTH,IOUTNO) !! 
  CALL SELF%YRML_PHY_STOCH%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YRML_PHY_MF%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YRML_CHEM%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YRML_DIAG%PRINT(ITOPDEPTH,IOUTNO)
  CALL SELF%YREWCOU%PRINT(ITOPDEPTH,IOUTNO)

  WRITE(IOUTNO,*) 'MODEL Object print : END '
  WRITE(IOUTNO,*) '=============================================='
  WRITE(IOUTNO,*) ''
  WRITE(IOUTNO,*) ''


  IF (PRESENT(KOUTNO)) CLOSE(IOUTNO)

END SUBROUTINE PRINT_MODEL_CONFIGURATION

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_FINAL(THIS)
  TYPE(MODEL) :: THIS
  ! If we don't add this, we may get a internal compiler error
END SUBROUTINE MODEL_FINAL

END MODULE TYPE_MODEL
