MODULE YOECLD

USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

SAVE

!     -----------------------------------------------------------------
!*    ** *YOECLD* - CONTROL PARAMETERS FOR DIAGNOSTIC CLOUDS
!     -----------------------------------------------------------------

TYPE :: TECLD
REAL(KIND=JPRB),ALLOCATABLE:: CETA(:)

REAL(KIND=JPRB) :: RANVA
REAL(KIND=JPRB) :: RANVB
REAL(KIND=JPRB) :: RANVH
REAL(KIND=JPRB) :: RCCA
REAL(KIND=JPRB) :: RCCB
REAL(KIND=JPRB) :: RCCC
REAL(KIND=JPRB) :: RCFCT
REAL(KIND=JPRB) :: RCLWMR
REAL(KIND=JPRB) :: RCSCAL
REAL(KIND=JPRB) :: RDECORR_CF
REAL(KIND=JPRB) :: RDECORR_CW
REAL(KIND=JPRB) :: RETAHB
REAL(KIND=JPRB) :: RETAMB
REAL(KIND=JPRB) :: RLOIA
REAL(KIND=JPRB) :: RLOIB
REAL(KIND=JPRB) :: RLOIC
REAL(KIND=JPRB) :: RLOID
REAL(KIND=JPRB) :: RLONIA
REAL(KIND=JPRB) :: RLONIB
REAL(KIND=JPRB) :: RRHH
REAL(KIND=JPRB) :: RRHL
REAL(KIND=JPRB) :: RGAMMAS
REAL(KIND=JPRB) :: REPSCR
REAL(KIND=JPRB) :: REPSEC
LOGICAL :: LOMEGA
!----------------------------------------------------------------------------
CONTAINS
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
END TYPE TECLD
!============================================================================

!!TYPE(TECLD), POINTER :: YRECLD => NULL()

!        * E.C.M.W.F. PHYSICS PACKAGE *

!     J.-J. MORCRETTE       E.C.M.W.F.      89/07/14

!  NAME     TYPE     PURPOSE
!  ----  :  ----   : ---------------------------------------------------
!  RANVA :  REAL     COEFFICIENT FOR ANVIL CLOUDS
!  RANVB :  REAL     COEFFICIENT FOR ANVIL CLOUDS
!  RANVH :  REAL     MINIMUM HIGH CLOUD COVER FOR ANVIL CLOUDS
!  RCCA  :  REAL     COEFFICIENT FOR DIAGNOSTIC OF CONVECTIVE CLOUD
!  RCCB  :  REAL     COEFFICIENT FOR DIAGNOSTIC OF CONVECTIVE CLOUD
!  RCCC  :  REAL     MAXIMUM COVER BY CONVECTIVE CLOUD
!  RCFCT :  REAL     WEIGHTING FACTOR FOR CONVECTIVE CLOUD TOWER
!  RCLWMR:  REAL     LIQUID WATER MIXING RATIO FOR CONVECTIVE CLOUD
!  RCSCAL:  REAL     SCALING FACTOR FOR CONVECTIVE RAIN
!  CETA(NFLEVG) REAL  MODEL REFERENCE ETA-LEVEL
!  RDECORR_CF:  REAL  DECORR. DEPTH FOR GENERALISED CLOUD OVERLAP (CLOUD FRAC)
!  RDECORR_CW:  REAL  DECORR. DEPTH FOR GENERALISED CLOUD OVERLAP (CONDENSATE)
!  RETAHB:  REAL     ETA-LEVEL LIMIT FOR HIGH CLOUDS
!  RETAMB:  REAL     ETA-LEVEL LIMIT FOR MEDIUM CLOUDS
!  RLOIA :  REAL     COEFFICIENT FOR LOW CLOUD WHEN NO INVERSION
!  RLOIB :  REAL     COEFFICIENT FOR LOW CLOUD WHEN INVERSION
!  RLOIC :  REAL     COEFFICIENT FOR LOW CLOUD WHEN INVERSION
!  RLOID :  REAL     COEFFICIENT FOR LOW CLOUD WHEN INVERSION
!  RLONIA:  REAL     COEFFICIENT FOR LOW CLOUD WHEN INVERSION
!  RLONIB:  REAL     COEFFICIENT FOR LOW CLOUD WHEN NO INVERSION
!  RRHH  :  REAL     CRITICAL RELATIVE HUMIDITY FOR HIGH CLOUDS
!  RRHL  :  REAL     CRITICAL RELATIVE HUMIDITY FOR LOW CLOUDS
!  GAMMAS:  REAL     PROPORTIONALITY FACTOR FOR LIQUID WATER CONTENT
!  REPSCR:  REAL     MINIMUM CONVECTIVE PRECIPITATION (SECURITY FACTOR)
!  REPSEC:  REAL     MINIMUM HORIZONTAL CLOUD COVER (SECURITY FACTOR)
!  LOMEGA:  LOGICAL  SWITCH FOR OMEGA-FILTER ON MIDDLE CLOUD
!     ------------------------------------------------------------------

CONTAINS

SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  IMPLICIT NONE
  CLASS(TECLD), INTENT(IN) :: SELF
  INTEGER     , INTENT(IN) :: KDEPTH
  INTEGER     , INTENT(IN) :: KOUTNO

  INTEGER :: IDEPTHLOC

  IDEPTHLOC = KDEPTH+2
  
  WRITE(KOUTNO,*) REPEAT(' ',KDEPTH   ) // 'model%yrml_phy_ec%yrecld : '
  IF (ALLOCATED(SELF%CETA)) WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'CETA allocated of shape ', SHAPE(SELF%CETA),' sum ',SUM(SELF%CETA)
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RANVA = ', SELF%RANVA
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RANVB = ', SELF%RANVB
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RANVH = ', SELF%RANVH
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RCCA = ', SELF%RCCA
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RCCB = ', SELF%RCCB
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RCCC = ', SELF%RCCC
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RCFCT = ', SELF%RCFCT
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RCLWMR = ', SELF%RCLWMR
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RCSCAL = ', SELF%RCSCAL
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RDECORR_CF = ', SELF%RDECORR_CF
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RDECORR_CW = ', SELF%RDECORR_CW
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RETAHB = ', SELF%RETAHB
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RETAMB = ', SELF%RETAMB
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RLOIA = ', SELF%RLOIA
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RLOIB = ', SELF%RLOIB
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RLOIC = ', SELF%RLOIC
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RLOID = ', SELF%RLOID
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RLONIA = ', SELF%RLONIA
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RLONIB = ', SELF%RLONIB
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RRHH = ', SELF%RRHH
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RRHL = ', SELF%RRHL
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RGAMMAS = ', SELF%RGAMMAS
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'REPSCR = ', SELF%REPSCR
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'REPSEC = ', SELF%REPSEC
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'LOMEGA = ', SELF%LOMEGA
 
END SUBROUTINE PRINT_CONFIGURATION

END MODULE YOECLD
