interface
SUBROUTINE RRTM_ECRT_140GP_MCICA&
 &(YDDIMV, YDEAERATM,YDERAD,YGFL,KIDIA, KFDIA, KLON, KLEV, KCOLS ,&
 &PAER , PAPH , PAP , PAERTAUL, PAERASYL, PAEROMGL,&
 &PTS , PTH , PT ,&
 &PEMIS, PEMIW,&
 &PQ , PCO2 , PCH4, PN2O , PNO2, PC11, PC12, PC22, PCL4, POZN, PCLDF , PTAUCLDI,&
 &PCLDFRAC, PTAUCLD, PCOLDRY, PWBRODL, PWKL, PWX ,&
 & PTAUAERL, PAVEL , PTAVEL , PZ , PTZ , PTBOUND, PSEMISS , KREFLECT)
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE PARRRTM , ONLY : JPBAND, JPXSEC, JPINPX
USE YOERAD , ONLY : TERAD
USE YOEAERATM, ONLY : TEAERATM
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TEAERATM) ,INTENT(INOUT) :: YDEAERATM
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KCOLS
REAL(KIND=JPRB) ,INTENT(IN) :: PAER(KLON,6,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERTAUL(KLON,KLEV,16), PAERASYL(KLON,KLEV,16), PAEROMGL(KLON,KLEV,16)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCO2(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCH4(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PN2O(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNO2(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PC11(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PC12(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PC22(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL4(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POZN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLDF(KLON,KCOLS,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAUCLDI(KLON,KLEV,KCOLS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLDFRAC(KIDIA:KFDIA,KCOLS,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTAUCLD(KIDIA:KFDIA,YDDIMV%NFLEVG,KCOLS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOLDRY(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWBRODL(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWKL(KIDIA:KFDIA,JPINPX,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWX(KIDIA:KFDIA,JPXSEC,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTAUAERL(KIDIA:KFDIA,YDDIMV%NFLEVG,JPBAND)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAVEL(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTAVEL(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZ(KIDIA:KFDIA,0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTZ(KIDIA:KFDIA,0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTBOUND(KIDIA:KFDIA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSEMISS(KIDIA:KFDIA,JPBAND)
INTEGER(KIND=JPIM),INTENT(OUT) :: KREFLECT(KIDIA:KFDIA)
END SUBROUTINE RRTM_ECRT_140GP_MCICA
end interface
