interface
SUBROUTINE SRTM_INIT(DIRECTORY, NWVCONTINUUM)
use parkind1 , only:&
 & jpim
CHARACTER(LEN=*), INTENT(IN) :: DIRECTORY
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: NWVCONTINUUM
END SUBROUTINE SRTM_INIT
end interface
