interface
SUBROUTINE SRTM_SRTM_224GP_MCICA&
 & (YDDIMV, YDML_PHY_RAD,YGFL,YDPHY3,KIDIA, KFDIA, KLON , KLEV , KSW , KCOLS , KCLDLY ,&
 & PAER , PALBD, PALBP, PAPH , PAP , PAERTAUS, PAERASYS, PAEROMGS ,&
 & PTS , PTH , PT ,&
 & PQ , PCO2 , PCH4 , PN2O , PNO2 , POZN , PRMU0 ,&
 & PFRCL, PTAUC, PASYC, POMGC,&
 & PFSUX, PFSUC, PFUVF, PFUVC, PPARF, PPARCF, PSUDU ,&
 & PFDIR, PCDIR, PFDIF, PCDIF, PSWDIFFUSEBAND, PSWDIRECTBAND)
USE MODEL_PHYSICS_RADIATION_MOD , ONLY : MODEL_PHYSICS_RADIATION_TYPE
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMPHY3 , ONLY : TPHY3
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(MODEL_PHYSICS_RADIATION_TYPE),INTENT(INOUT):: YDML_PHY_RAD
TYPE(TPHY3) ,INTENT(INOUT) :: YDPHY3
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSW
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KCOLS
INTEGER(KIND=JPIM),INTENT(IN) :: KCLDLY(KCOLS)
REAL(KIND=JPRB) ,INTENT(IN) :: PAER(KLON,6,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERTAUS(KLON,KLEV,14), PAERASYS(KLON,KLEV,14), PAEROMGS(KLON,KLEV,14)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBD(KLON,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBP(KLON,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCO2(KLON,KLEV), PCH4(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PN2O(KLON,KLEV), PNO2(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POZN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRMU0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRCL(KLON,KCOLS,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAUC(KLON,KCOLS,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PASYC(KLON,KCOLS,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POMGC(KLON,KCOLS,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSUX(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSUC(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFUVF(KLON), PFUVC(KLON), PPARF(KLON), PPARCF(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSUDU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFDIF(KLON,KLEV+1), PCDIF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFDIR(KLON,KLEV+1), PCDIR(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSWDIFFUSEBAND(KLON,YDML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSWDIRECTBAND (KLON,YDML_PHY_RAD%YRERAD%NSW)
END SUBROUTINE SRTM_SRTM_224GP_MCICA
end interface
