interface
SUBROUTINE SRTM_SPCVRT_MCICA&
 & (YDDIMV, YDERAD,YDERDI,KIDIA , KFDIA , KLEV , KSW , KCOLS , PONEMINUS,&
 & PALBD , PALBP,&
 & PFRCL , PTAUC , PASYC , POMGC , PTAUA , PASYA , POMGA , PRMU0,&
 & KLAYTROP,&
 & PCOLCH4 , PCOLCO2 , PCOLH2O , PCOLMOL , PCOLO2 , PCOLO3 ,&
 & PFORFAC , PFORFRAC , KINDFOR , PSELFFAC, PSELFFRAC, KINDSELF ,&
 & PFAC00 , PFAC01 , PFAC10 , PFAC11 ,&
 & KJP , KJT , KJT1 ,&
 & PBBFD , PBBFU , PBBCD, PBBCU, PFUVF, PFUVC, PPARF, PPARCF, PSUDU,&
 & PBBFDIR , PBBCDIR , PSWDIFFUSEBAND , PSWDIRECTBAND )
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOERDI , ONLY : TERDI
USE YOERAD , ONLY : TERAD
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(TERDI) ,INTENT(INOUT) :: YDERDI
INTEGER(KIND=JPIM),INTENT(IN) :: KSW
INTEGER(KIND=JPIM),INTENT(IN) :: KCOLS
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PONEMINUS(KIDIA:KFDIA)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBD(KIDIA:KFDIA,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBP(KIDIA:KFDIA,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRCL(KIDIA:KFDIA,KCOLS,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAUC(KIDIA:KFDIA,YDDIMV%NFLEVG,KCOLS)
REAL(KIND=JPRB) ,INTENT(IN) :: PASYC(KIDIA:KFDIA,YDDIMV%NFLEVG,KCOLS)
REAL(KIND=JPRB) ,INTENT(IN) :: POMGC(KIDIA:KFDIA,YDDIMV%NFLEVG,KCOLS)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAUA(KIDIA:KFDIA,YDDIMV%NFLEVG,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PASYA(KIDIA:KFDIA,YDDIMV%NFLEVG,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: POMGA(KIDIA:KFDIA,YDDIMV%NFLEVG,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PRMU0(KIDIA:KFDIA)
INTEGER(KIND=JPIM),INTENT(IN) :: KLAYTROP(KIDIA:KFDIA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOLCH4(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOLCO2(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOLH2O(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOLMOL(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOLO2(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOLO3(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORFAC(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORFRAC(KIDIA:KFDIA,YDDIMV%NFLEVG)
INTEGER(KIND=JPIM),INTENT(IN) :: KINDFOR(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSELFFAC(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSELFFRAC(KIDIA:KFDIA,YDDIMV%NFLEVG)
INTEGER(KIND=JPIM),INTENT(IN) :: KINDSELF(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFAC00(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFAC01(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFAC10(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFAC11(KIDIA:KFDIA,YDDIMV%NFLEVG)
INTEGER(KIND=JPIM),INTENT(IN) :: KJP(KIDIA:KFDIA,YDDIMV%NFLEVG)
INTEGER(KIND=JPIM),INTENT(IN) :: KJT(KIDIA:KFDIA,YDDIMV%NFLEVG)
INTEGER(KIND=JPIM),INTENT(IN) :: KJT1(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBBFD(KIDIA:KFDIA,YDDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBBFU(KIDIA:KFDIA,YDDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBBCD(KIDIA:KFDIA,YDDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBBCU(KIDIA:KFDIA,YDDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFUVF(KIDIA:KFDIA), PFUVC(KIDIA:KFDIA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPARF(KIDIA:KFDIA), PPARCF(KIDIA:KFDIA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSUDU(KIDIA:KFDIA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBBFDIR(KIDIA:KFDIA,YDDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBBCDIR(KIDIA:KFDIA,YDDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSWDIFFUSEBAND(KIDIA:KFDIA,YDERAD%NSW)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSWDIRECTBAND(KIDIA:KFDIA,YDERAD%NSW)
END SUBROUTINE SRTM_SPCVRT_MCICA
end interface
