SUBROUTINE ABOR1(CDTEXT)

USE PARKIND1,      ONLY : JPIM, JPRB
USE YOMLUN_IFSAUX, ONLY : NULOUT, NULERR

IMPLICIT NONE

CHARACTER(LEN=*), INTENT(IN) :: CDTEXT

IF (NULOUT >= 0) WRITE(NULOUT,'(1X,A)') CDTEXT
IF (NULERR >= 0) WRITE(NULERR,'(1X,A,A)') 'ABORT! ', CDTEXT

IF (NULOUT >= 0) THEN
  CALL FLUSH(NULOUT)
  IF (NULOUT /= 0 .and. NULOUT /= 6) CLOSE(NULOUT)
ENDIF

CALL ABORT

END SUBROUTINE ABOR1
