MODULE YOMLUN

USE PARKIND1,      ONLY : JPIM
USE YOMLUN_IFSAUX, ONLY : NULOUT, NULERR

IMPLICIT NONE

PUBLIC

SAVE

INTEGER(KIND=JPIM) :: NULRAD = 25

!     ------------------------------------------------------------------
END MODULE YOMLUN
