SUBROUTINE CDRHOOKINIT(KRET)
!-- Makes sure Dr.Hook gets properly initialized from C-main program, too
USE PARKIND1  ,ONLY  : JPIM, JPRB, JPRD
USE YOMHOOK   ,ONLY  : LHOOK, DR_HOOK
IMPLICIT NONE
INTEGER(KIND=JPIM), INTENT(OUT) :: KRET
REAL(KIND=JPRD) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CDRHOOKINIT',0,ZHOOK_HANDLE)
IF (LHOOK) THEN
  KRET = 1 ! Dr.Hook is ON
ELSE
  KRET = 0 ! Dr.Hook is OFF
ENDIF
IF (LHOOK) CALL DR_HOOK('CDRHOOKINIT',1,ZHOOK_HANDLE)
END SUBROUTINE CDRHOOKINIT
