SUBROUTINE DR_HOOK_PROCINFO(KMYPROC, KNPROC)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE MPL_MODULE, ONLY : MPL_WORLD_RANK, MPL_WORLD_SIZE
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(OUT) :: KMYPROC, KNPROC
KMYPROC = MPL_WORLD_RANK + 1
KNPROC = MPL_WORLD_SIZE
END SUBROUTINE DR_HOOK_PROCINFO
