FUNCTION GET_NUM_THREADS() RESULT(INUMT)
USE PARKIND1  ,ONLY : JPIM
USE OML_MOD, ONLY : OML_NUM_THREADS
IMPLICIT NONE
INTEGER(KIND=JPIM) :: INUMT
INUMT = 1
!$ inumt = OML_NUM_THREADS()
END FUNCTION GET_NUM_THREADS
