FUNCTION GET_MAX_THREADS() RESULT(IMAXT)
USE PARKIND1  ,ONLY : JPIM
USE OML_MOD, ONLY : OML_MAX_THREADS
IMPLICIT NONE
INTEGER(KIND=JPIM) :: IMAXT
IMAXT = 1
!$ imaxt = OML_MAX_THREADS()
END FUNCTION GET_MAX_THREADS
