MODULE MPL_COMM_SPLIT_MOD

!**** *MPL_COMM_SPLIT* - Split a communicator

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012


USE PARKIND1, ONLY : JPIM 
USE MPL_MPIF, ONLY : MPI_UNDEFINED

IMPLICIT NONE

PRIVATE
PUBLIC MPL_COMM_SPLIT

CONTAINS 

SUBROUTINE MPL_COMM_SPLIT (KCOMM, KCOLOR, KKEY, KNEWCOMM, KERROR, CDSTRING)
INTEGER (KIND=JPIM), INTENT (IN)  :: KCOMM
INTEGER (KIND=JPIM), INTENT (IN)  :: KCOLOR
INTEGER (KIND=JPIM), INTENT (IN)  :: KKEY
INTEGER (KIND=JPIM), INTENT (OUT) :: KNEWCOMM
INTEGER (KIND=JPIM), INTENT (OUT) :: KERROR
CHARACTER (LEN=*), OPTIONAL, INTENT (IN) :: CDSTRING
INTEGER (KIND=JPIM) :: ICOLOR

ICOLOR=KCOLOR
IF(ICOLOR<0) ICOLOR=MPI_UNDEFINED

CALL MPI_COMM_SPLIT (KCOMM, ICOLOR, KKEY, KNEWCOMM, KERROR)

END SUBROUTINE MPL_COMM_SPLIT

END MODULE MPL_COMM_SPLIT_MOD
