MODULE MPL_COMM_FREE_MOD

!**** *MPL_COMM_FREE_MOD*  - Release ressources used by a communicator

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012

USE PARKIND1, ONLY : JPIM

IMPLICIT NONE

PRIVATE
PUBLIC :: MPL_COMM_FREE

CONTAINS

SUBROUTINE MPL_COMM_FREE (KCOMM, KERR, CDSTRING)
INTEGER (KIND=JPIM), INTENT (IN)  :: KCOMM
INTEGER (KIND=JPIM), INTENT (OUT) :: KERR
CHARACTER (LEN=*),   INTENT (IN), OPTIONAL :: CDSTRING

CALL MPI_COMM_FREE (KCOMM, KERR)

END SUBROUTINE MPL_COMM_FREE

END MODULE MPL_COMM_FREE_MOD
