INTERFACE
SUBROUTINE COMPUTE_LAYTROP_MIN_MAX(KIDIA,KFDIA,LAYTROP,laytrop_min,laytrop_max)
  USE PARKIND1  ,ONLY : JPIM
  IMPLICIT NONE
  INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
  INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
  INTEGER(KIND=JPIM),INTENT(IN)    :: LAYTROP(KIDIA:KFDIA)
  INTEGER(KIND=JPIM),INTENT(INOUT) :: laytrop_min, laytrop_max
END SUBROUTINE COMPUTE_LAYTROP_MIN_MAX
END INTERFACE
