name: check-pr

concurrency:
  group: prtk-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review, converted_to_draft]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check-pr:
    if: github.repository_owner == 'ecmwf-ifs'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.12
          enable-cache: false

      - name: Install prtk
        env:
          PRTK_READ_ACCESS_TOKEN: ${{ secrets.PRTK_READ_ACCESS }}
        run: |
          uv tool install "git+https://${PRTK_READ_ACCESS_TOKEN}@github.com/ecmwf-ifs/prtk"

      - name: Run prtk checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          prtk check
          --pr-number "${{ github.event.pull_request.number }}"
          --default-branch "${{ github.event.repository.default_branch }}"
          --event-name "${{ github.event_name }}"
          --event-action "${{ github.event.action }}"
